# Generated by Django 5.2.7 on 2026-03-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_notice_date_notice_created_at_notice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fees',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fees',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
