# Generated by Django 5.2.7 on 2026-03-27 14:15

import django.db.models.deletion
from django.db import migrations, models


def forwards_teacher_subject_to_fk(apps, schema_editor):
    Teacher = apps.get_model('school', 'Teacher')
    Subject = apps.get_model('school', 'Subject')
    db_alias = schema_editor.connection.alias

    for teacher in Teacher.objects.using(db_alias).all():
        old_value = getattr(teacher, 'subject', None)
        if not old_value:
            continue

        # old_value is a string from the legacy CharField
        subj, _ = Subject.objects.using(db_alias).get_or_create(name=str(old_value).strip())
        teacher.subject_fk = subj
        teacher.save(update_fields=['subject_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_address_student_blood_group_student_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_periods',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject'),
        ),
        migrations.RunPython(forwards_teacher_subject_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_fk',
            new_name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'period', 'subject')},
        ),
    ]
