# Generated by Django 5.2.7 on 2026-03-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_mark_max_marks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'period')},
        ),
    ]
