# Generated by Django 5.2.7 on 2026-03-31 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee_amount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Extra Activities',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='mark',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='career_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('total_fee', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.extraactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to='school.student')),
            ],
            options={
                'verbose_name': 'Student Activity Registration',
                'verbose_name_plural': 'Student Activity Registrations',
                'unique_together': {('student', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='ActivityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.studentactivityregistration')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='extra_activities',
            field=models.ManyToManyField(blank=True, through='school.StudentActivityRegistration', to='school.extraactivity'),
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('qualification', 'Qualification'), ('experience', 'Experience Letter'), ('id_proof', 'ID Proof'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='teacher_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_salary', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('pending_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='school.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher Salaries',
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.teachersalary')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='period',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
