# Generated by Django 5.2.7 on 2026-03-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_extraactivity_loginhistory_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_periods',
        ),
    ]
