# Generated by Django 5.2.7 on 2026-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_course_total_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.TextField(blank=True, help_text='Enter subjects separated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
